import type { NextPage } from "next";
import Head from "next/head";
import {
    Anchor,
    Box,
    Grommet,
    Header,
    Menu,
    Nav,
    ResponsiveContext
} from "grommet";
import styles from "../styles/Home.module.css";
import Balance from "../assets/analytics.svg";
import Income from "../assets/inbox-in.svg";
import Expense from "../assets/inbox-out.svg";
import Savings from "../assets/piggy-bank.svg";
import Debt from "../assets/chart-line-down.svg";
import Planning from "../assets/sliders-h.svg";
import Settings from "../assets/cog.svg";
import Logout from "../assets/sign-out.svg";

const Home: NextPage = () => {
    return (
        <Grommet plain>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Header background="dark-1" pad="medium">
                    <Box direction="row" align="center" gap="small">
                        {/*TODO add transaction record button*/}
                    </Box>
                    <ResponsiveContext.Consumer>
                        {responsive =>
                            responsive === "small" ? (
                                <Menu
                                    size={"small"}
                                    items={[
                                        {
                                            label: "Balance",
                                            onClick: () => {},
                                            icon: (
                                                <Box pad="small">
                                                    <Balance
                                                        fill="#ecebed"
                                                        className={styles.icon}
                                                    />
                                                </Box>
                                            )
                                        },
                                        {
                                            label: "Income",
                                            onClick: () => {},
                                            icon: (
                                                <Box pad="small">
                                                    <Income
                                                        fill="#ecebed"
                                                        className={styles.icon}
                                                    />
                                                </Box>
                                            )
                                        },
                                        {
                                            label: "Expense",
                                            onClick: () => {},
                                            icon: (
                                                <Box pad="small">
                                                    <Expense
                                                        fill="#ecebed"
                                                        className={styles.icon}
                                                    />
                                                </Box>
                                            )
                                        },
                                        {
                                            label: "Savings",
                                            onClick: () => {},
                                            icon: (
                                                <Box pad="small">
                                                    <Savings
                                                        fill="#ecebed"
                                                        className={styles.icon}
                                                    />
                                                </Box>
                                            )
                                        },
                                        {
                                            label: "Debt",
                                            onClick: () => {},
                                            icon: (
                                                <Box pad="small">
                                                    <Debt
                                                        fill="#ecebed"
                                                        className={styles.icon}
                                                    />
                                                </Box>
                                            )
                                        },
                                        {
                                            label: "Planning",
                                            onClick: () => {},
                                            icon: (
                                                <Box pad="small">
                                                    <Planning
                                                        fill="#ecebed"
                                                        className={styles.icon}
                                                    />
                                                </Box>
                                            )
                                        },
                                        {
                                            label: "Settings",
                                            onClick: () => {},
                                            icon: (
                                                <Box pad="small">
                                                    <Settings
                                                        fill="#ecebed"
                                                        className={styles.icon}
                                                    />
                                                </Box>
                                            )
                                        },
                                        {
                                            label: "Log out",
                                            onClick: () => {},
                                            icon: (
                                                <Box pad="small">
                                                    <Logout
                                                        fill="#ecebed"
                                                        className={styles.icon}
                                                    />
                                                </Box>
                                            )
                                        }
                                    ]}
                                />
                            ) : (
                                <Nav direction="row">
                                    <Anchor
                                        color="#ecebed"
                                        href="#"
                                        label="Balance"
                                        icon={
                                            <Balance
                                                fill="#ecebed"
                                                className={styles.icon}
                                            />
                                        }
                                    />
                                    <Anchor
                                        color="#ecebed"
                                        href="#"
                                        label="Income"
                                        icon={
                                            <Income
                                                fill="#ecebed"
                                                className={styles.icon}
                                            />
                                        }
                                    />
                                    <Anchor
                                        color="#ecebed"
                                        href="#"
                                        label="Expense"
                                        icon={
                                            <Expense
                                                fill="#ecebed"
                                                className={styles.icon}
                                            />
                                        }
                                    />
                                    <Anchor
                                        color="#ecebed"
                                        href="#"
                                        label="Savings"
                                        icon={
                                            <Savings
                                                fill="#ecebed"
                                                className={styles.icon}
                                            />
                                        }
                                    />
                                    <Anchor
                                        color="#ecebed"
                                        href="#"
                                        label="Debt"
                                        icon={
                                            <Debt
                                                fill="#ecebed"
                                                className={styles.icon}
                                            />
                                        }
                                    />
                                    <Anchor
                                        color="#ecebed"
                                        href="#"
                                        label="Planning"
                                        icon={
                                            <Planning
                                                fill="#ecebed"
                                                className={styles.icon}
                                            />
                                        }
                                    />
                                    <Anchor
                                        color="#ecebed"
                                        href="#"
                                        label="Settings"
                                        icon={
                                            <Settings
                                                fill="#ecebed"
                                                className={styles.icon}
                                            />
                                        }
                                    />
                                    <Anchor
                                        color="#ecebed"
                                        href="#"
                                        label="Log out"
                                        icon={
                                            <Logout
                                                fill="#ecebed"
                                                className={styles.icon}
                                            />
                                        }
                                    />
                                </Nav>
                            )
                        }
                    </ResponsiveContext.Consumer>
                </Header>
            </main>
        </Grommet>
    );
};

export default Home;
